name: chat-ui ci

on:
  push:
    branches: [ "main" ]
    paths:
      - "chat-ui/**"
      - ".github/workflows/chat-ui-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "chat-ui/**"
      - ".github/workflows/chat-ui-ci.yaml"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      FROM_ORIGINAL_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: chat-ui
      - run: npm run build
        working-directory: chat-ui
      - run: npm run lint
        working-directory: chat-ui
      - run: npx prettier --check .
        working-directory: chat-ui
      - name: SonarCloud Scan
        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: chat-ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: ./chat-ui
          push: true
          tags: ghcr.io/nashtech-garage/ntg-jvm-agent-chat-ui:latest