name:  Build Kotlin app

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build chat ui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orchestrator
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: chat-ui/package-lock.json


      - name: Install dependencies
        run: npm ci # or `npm install` if lock file doesn't exist
        working-directory: chat-ui

      - name: Build app (React)
        run: npm run build
        working-directory: chat-ui
