name:  Build Kotlin app

on:
  pull_request:
    types: [ opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  authorization-server:
    name: Build Kotlin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build and test all modules
        run: mvn clean install
