name:  Build Kotlin app

on:
  push:
    paths:
      - 'orchestrator/**'
  pull_request:
    paths:
      - 'orchestrator/**'

jobs:
  build:
    name: Build Orchestrator
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: orchestrator
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build and test all modules
        run: mvn clean install
